version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /cds-containers/go-dev-1.24-alpine
      - /cds-containers/go-dev-1.24-debian
      - /cds-containers/tools
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      container-base-images:
        patterns:
          - "*"
